### ISSUE TITLE
Optimization Target Must be a Link

### ISSUE THREAD

**Issue by atom2k17** [tochikuji/chainer-libDNN#5]
StackedAutoEncoder Class is not made of links as it is inherited from NNBase. So when trying to set sda = StackedAutoEncoder(model) we are getting an error in set_optimizer saying **TypeError:** **optimization target must be a link** . How to set optimizer and how to handle this issue?

**Comment by tochikuji** [comment]
This library has been about to become a wrapper script of the past that is for legacy chainer (<1.4.0) when the model is not a `Link` or `Chain` class but also a `FuctionSet`. So you cannot apply this SAE implementation for the modern chainer library 😢 
But the concept of the `StackedAutoEncoder` class could be of service for your implementation. https://github.com/tochikuji/chainer-libDNN/blob/master/libdnn/autoencoder.py#L71
